stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Hello, World! from Build Stage"

test:
  stage: test
  script:
    - echo "Hello, World! from Test Stage"

deploy:
  stage: deploy
  script:
    - echo "Hello, World! from Deploy Stage"

